<?php

namespace Container0SpGFPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KuwsKVUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kuwsKVU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kuwsKVU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiPatientController::index' => ['privates', '.service_locator.IgZFGVs', 'get_ServiceLocator_IgZFGVsService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator..WbzsKm', 'get_ServiceLocator__WbzsKmService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.Isyi.eu', 'get_ServiceLocator_Isyi_EuService', true],
            'App\\Controller\\OrdonanceController::index' => ['privates', '.service_locator._8zpnNz', 'get_ServiceLocator_8zpnNzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ApiPatientController:index' => ['privates', '.service_locator.IgZFGVs', 'get_ServiceLocator_IgZFGVsService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator..WbzsKm', 'get_ServiceLocator__WbzsKmService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.Isyi.eu', 'get_ServiceLocator_Isyi_EuService', true],
            'App\\Controller\\OrdonanceController:index' => ['privates', '.service_locator._8zpnNz', 'get_ServiceLocator_8zpnNzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ApiPatientController::index' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\OrdonanceController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ApiPatientController:index' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\OrdonanceController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
