<?php

namespace Container0SpGFPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8zpnNzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._8zpnNz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._8zpnNz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ordonanceRepository' => ['privates', 'App\\Repository\\OrdonanceRepository', 'getOrdonanceRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
        ], [
            'ordonanceRepository' => 'App\\Repository\\OrdonanceRepository',
            'serializer' => '?',
        ]);
    }
}
