<?php

namespace ContainerOdsBjLH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssureurRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AssureurRepository' shared autowired service.
     *
     * @return \App\Repository\AssureurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AssureurRepository'] = new \App\Repository\AssureurRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
