<?php

namespace ContainerOdsBjLH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdonanceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OrdonanceController' shared autowired service.
     *
     * @return \App\Controller\OrdonanceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\OrdonanceController'] = $instance = new \App\Controller\OrdonanceController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\OrdonanceController', $container));

        return $instance;
    }
}
