<?php

namespace ContainerOdsBjLH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReglementRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ReglementRepository' shared autowired service.
     *
     * @return \App\Repository\ReglementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ReglementRepository'] = new \App\Repository\ReglementRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
